- packages/apify/src/configuration.ts
Quick follow-up to https://github.com/apify/crawlee/pull/1433
We talked about chaning the second example some time ago. So here's it :) 
For reference, your message (I don't really remember where you sent it, but I had it in my notes =D )
> this example should be about global configuration, while its using the same approach as the previous one, it just instantiates the config instead of actor class but its exactly the same use case.
> 
> in v2 we have this simple example, which is indeed too bare bones
> 
> [apify-js/configuration.js at master · apify/apify-js](https://github.com/apify/apify-js/blob/master/src/configuration.js#L20)
> 
> i guess we should showcase that the Configuration.getGlobalConfig() is used automaticaly, e.g. by setting the persistStateIntervalMillis on it and not …
> docs: update configuration example

- docs/examples/add_data_to_dataset.mdx
- docs/examples/crawl_relative_links.mdx
- docs/examples/crawl_some_links.mdx
- docs/examples/forms.mdx
- docs/examples/map_and_reduce.mdx
- docs/examples/playwright_crawler.mdx
- docs/examples/puppeteer_crawler.mdx
- docs/guides/apify_platform.mdx
- docs/guides/environment_variables.mdx
- docs/guides/proxy_management.mdx
- docs/guides/request_storage.mdx
- docs/guides/result_storage.mdx
- docs/guides/session_management.mdx
- website/src/components/ApiLink.jsx
- website/versioned_docs/version-3.0/examples/add_data_to_dataset.mdx
- website/versioned_docs/version-3.0/examples/crawl_relative_links.mdx
- website/versioned_docs/version-3.0/examples/crawl_some_links.mdx
- website/versioned_docs/version-3.0/examples/forms.mdx
- website/versioned_docs/version-3.0/examples/map_and_reduce.mdx
- website/versioned_docs/version-3.0/examples/playwright_crawler.mdx
- website/versioned_docs/version-3.0/examples/puppeteer_crawler.mdx
- website/versioned_docs/version-3.0/guides/environment_variables.mdx
- website/versioned_docs/version-3.0/guides/proxy_management.mdx
- website/versioned_docs/version-3.0/guides/request_storage.mdx
- website/versioned_docs/version-3.0/guides/result_storage.mdx
- website/versioned_docs/version-3.0/guides/session_management.mdx
The `ApiLink.tsx` URL update is a bit janky (and so is the logic behind the URLs), ideas welcome.
> docs: fix broken ApiLink (v3.0)

- package-lock.json
- package.json
- test/apify/actor.test.ts
> chore: convert some tests to use spies instead of property overrides

- packages/actor-scraper/cheerio-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/cheerio-scraper/README.md
- packages/actor-scraper/playwright-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/playwright-scraper/README.md
- packages/actor-scraper/puppeteer-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/puppeteer-scraper/README.md
- packages/actor-scraper/web-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/web-scraper/README.md
- Removed `(deprecated)` from `Pseudo-URLs` input option.
- Added required proxy usage to the `Upgrading` section.
Also explicitly mentioned in Readme/Proxy Configuration section that `Proxy is required to run the scraper.` to make it more visible.
> chore: update generic scrapers readme and input schema

- package-lock.json
- packages/apify/package.json
- packages/apify/src/cli.ts
I couldn't test this properly because of the `apify-cli` exported binary of the [same name](https://github.com/apify/apify-cli/blob/f0e428585ecc1181189d22908270f6e3efb6bad8/package.json#L21) - but afaik Crawlee does the same, so it should work just fine?
> feat: `npx apify` now calls apify-cli

- packages/actor-scraper/web-scraper/README.md
Related https://apifier.slack.com/archives/C046DU0E19V/p1674163410623009
The documentation on the proper usage of the Initial cookies fields is hidden behind a tooltip and two links (and Ctrl+F `login` in the README gave nothing interesting).
> docs: [web-scraper] add Initial cookies README section

- packages/apify/src/actor.ts
Removes the `[Status message]` prefix from the actual status message, leaves it in the logs.
> fix: log status message only once and without prefix

- packages/apify/src/platform_event_manager.ts
- website/versioned_docs/version-1.3/api/Apify.md
- website/versioned_docs/version-2.3/api/Apify.md
- website/versioned_docs/version-3.0/api-typedoc.json
Based on the discussion on Slack, the hint to abort the run during migration is wrong, and it actually completely aborts the run.
@B4nan Should I also update the versioned docs?
> docs: remove hint to abort the run during migration

- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- .github/workflows/test-and-release.yaml
- .github/workflows/test-e2e.yaml
We want to centralize the secrets used in GitHub workflows to be synced from Doppler, so this changes the secrets to the ones from there.
> chore: update GitHub workflow secrets

- .github/workflows/docs.yaml
This makes sure that the CloudFront cache is invalidated after the docs are deployed to GitHub pages.
> chore: invalidate CloudFront cache after GitHub Pages deploy

- jest.config.js
- packages/apify/src/actor.ts
- test/apify/actor.test.ts
The `Actor.getInput()` method can return `null` if the INPUT key is not present in the `KeyValueStorage`, which often forced people to check for the null value and throw. Now users can use `Actor.getInputOrThrow()` shortcut which does exactly that. The difference is in the return type, as instead of `T | null` you get just `T`.
> feat: add `Actor.getInputOrThrow()` method

- CODEOWNERS
- packages/apify/src/actor.ts
- website/package-lock.json
- website/package.json
The default (generic) status message from `Actor.exit` was always overriding the final status message from basic crawler (that has much more information). This removes the default messages from there, keeping the one from basic crawler.
Sidenote: maybe we should also add current concurrency to the status messages?
> fix: only print status message when explicitly provided in `Actor.exit()`

- packages/actor-scraper/cheerio-scraper/README.md
- packages/actor-scraper/jsdom-scraper/README.md
- packages/actor-scraper/playwright-scraper/README.md
- packages/actor-scraper/puppeteer-scraper/README.md
- packages/actor-scraper/web-scraper/README.md
The marketing team wants to promote the Actor monetization webinar in the READMEs of the generic actors. This PR adds a single banner on top of each of the READMEs.
> docs: add monetization webinar banner

- packages/actor-scraper/cheerio-scraper/README.md
- packages/actor-scraper/jsdom-scraper/README.md
- packages/actor-scraper/playwright-scraper/README.md
- packages/actor-scraper/puppeteer-scraper/README.md
- packages/actor-scraper/web-scraper/README.md
merge this to remove the Actor monetization banner after the event has passed.
Note that to propagate this change to the Console, the actors have to be rebuilt (one by one, manually 🙃)
> docs: remove the monetization banner and h1 from actors

- test/e2e/puppeteer-store-pagination-jquery/test.mjs
- test/e2e/puppeteer-store-pagination/test.mjs
- test/e2e/tools.mjs
- test/e2e/web-dev-mode/test.mjs
Took me so long testing and debugging why in heck tests kept exiting the crawler MID CRAWL... Thought it was some error thrown or navigation timeouts or something deeper, but it seems to have been just the timeout for runActor being too low 😢
> chore(e2e): increase timeout to leave more space for tests to finish

- packages/apify/src/actor.ts
- packages/apify/src/proxy_configuration.ts
- test/apify/actor.test.ts
- test/apify/proxy_configuration.test.ts
We use the proxy configuration in all the templates, as we want users to run behind a proxy all the times. This PR changes the internal mechanism to gracefully ignore the proxy configuration locally when we don't see a valid token or proxy password. This way, new users can run their actors locally without being logged in.
This is how a run without proxy password look like:
```
INFO  System info {"apifyVersion":"3.1.14","apifyClientVersion":"2.8.4","crawleeVersion":"3.7.1","osType":"Darwin","nodeVersion":"v20.9.0"}
WARN  ProxyConfiguration: No proxy password or token detected, running without proxy. To use Apify Proxy locally, provide options.password or "APIFY_PROXY_PASSWORD" environment variable. If you add the "APIFY_TOKEN" environment variable, the password will be automatically …
```
> feat: ignore proxy configuration locally if no valid token or password is found

- .github/workflows/release.yaml
- .github/workflows/test-and-release.yaml
- .github/workflows/test-e2e.yaml
Telling puppeteer to download the binaries from the (current|alternative)? server.
This should get fixed with puppeteer v22, but I'd like to release before that (WCC release waiting for this and I'm leaving on vacation on Sunday 😄 )
> chore: try to fix the puppeteer download in CI

- package-lock.json
- package.json
- packages/actor-scraper/cheerio-scraper/package.json
- packages/actor-scraper/cheerio-scraper/src/internals/crawler_setup.ts
- packages/actor-scraper/jsdom-scraper/package.json
- packages/actor-scraper/jsdom-scraper/src/internals/crawler_setup.ts
- packages/actor-scraper/playwright-scraper/package.json
- packages/actor-scraper/playwright-scraper/src/internals/crawler_setup.ts
- packages/actor-scraper/puppeteer-scraper/package.json
- packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts
- packages/actor-scraper/web-scraper/package.json
- packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts
- packages/scraper-tools/package.json
- packages/scraper-tools/src/context.ts
As part of the performance testing of the new request queue. 
We want to migrate all scraper to request queue v2 and see the performance impact on Apify backend.
Before we do that we will inform Apify support to have an idea about these changes and monitor the backend and potentially revert it back to previous version.
> refactor: use RequestQueueV2 for all Actor scrapers

- package-lock.json
- packages/apify/package.json
- packages/apify/src/actor.ts
- packages/apify/src/utils.ts
The SDK depends on `@crawlee/core`, but if the user installs an incompatible version of crawlee, they might end up with two installations of the `@crawlee/core` which means multiple static registers like the one for the global configuration, which breaks the integration, since the SDK will only touch the global config it sees, but it's a different one than the explicitly installed package.
Closes #237
> feat: validate crawlee versions in `Actor.init`

- packages/apify/src/key_value_store.ts
Crawlee 3.10+ now implements the `getPublicUrl()` too, returning local file URL pointing to the memory storage file. 
This PR handles changes the SDK variant of `getPublicUrl()` to use that when outside of the apify platform instead of always returning the platform path (just because the SDK gets imported).
> fix: respect `KVS.getPublicUrl()` from core when not on apify platform

- package-lock.json
- package.json
- packages/apify/src/configuration.ts
This PR adds Actor Standby port to the configuration.
> feat: add standby port to configuration

- packages/apify/src/configuration.ts
This PR adds the `standbyPort` to `ConfigurationOptions` so that calling `get` with it won't fail with a TS error.
> fix: add `standbyPort` to `ConfigurationOptions`

- packages/apify/src/configuration.ts
We need to explain to devs how to detect that their Actor was started in Standby mode, and the way to detect it is via the `APIFY_META_ORIGIN` environment variable. I wanted to add it also to `Actor.config`, so that we can direct them to `Actor.config` instead of reading the plain environment variable.
We already have it in the Python SDK: https://github.com/apify/apify-sdk-python/blob/master/src/apify/config.py#L97
> feat: add `metaOrigin` to `Actor.config`

- docs/guides/environment_variables.mdx
- docs/guides/request_storage.mdx
- docs/guides/session_management.mdx
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
- website/src/components/ApiLink.jsx
- website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
- website/versioned_docs/version-3.0/guides/environment_variables.mdx
- website/versioned_docs/version-3.0/guides/request_storage.mdx
- website/versioned_docs/version-3.1/guides/environment_variables.mdx
- website/versioned_docs/version-3.1/guides/request_storage.mdx
- website/versioned_docs/version-3.1/guides/session_management.mdx
- website/versioned_docs/version-3.2/guides/environment_variables.mdx
- website/versioned_docs/version-3.2/guides/request_storage.mdx
- website/versioned_docs/version-3.2/guides/session_management.mdx
- website/versioned_sidebars/version-1.3-sidebars.json
- website/versioned_sidebars/version-2.3-sidebars.json
Bumps the Docusaurus version to v3 and swaps the `docusaurus-plugin-typedoc-api` for our updated fork.
> docs: bump Docusaurus to v3

- website/package-lock.json
- website/package.json
Solves https://github.com/apify/apify-client-js/issues/591 in SDK documentation. Merges new features from upstream `docusaurus-plugin-typedoc-api`.
> docs: bump `@apify/docusaurus-plugin-typedoc-api`

- docs/guides/docker_images.mdx
- docs/guides/proxy_management.mdx
- docs/guides/session_management.mdx
- website/versioned_docs/version-3.0/guides/docker_images.mdx
- website/versioned_docs/version-3.0/guides/proxy_management.mdx
- website/versioned_docs/version-3.0/guides/session_management.mdx
- website/versioned_docs/version-3.1/guides/docker_images.mdx
- website/versioned_docs/version-3.1/guides/proxy_management.mdx
- website/versioned_docs/version-3.1/guides/session_management.mdx
- website/versioned_docs/version-3.2/guides/docker_images.mdx
- website/versioned_docs/version-3.2/guides/proxy_management.mdx
- website/versioned_docs/version-3.2/guides/session_management.mdx
Removes unnecessary `zero-width space` characters from the `mdx` files. The source of those is unclear - git blame says that they have been there since > 2 years ago. The on-page rendering remains the same with or without those characters.
Closes https://github.com/apify/apify-docs/issues/1262
> fix: remove zwsp characters from markdown docs

- package-lock.json
- packages/apify/package.json
- packages/apify/src/actor.ts
- packages/apify/src/utils.ts
The support for this was added in client v2.10 (https://github.com/apify/apify-client-js/pull/602/files#diff-c33bae26ce4a7b3559aef1321052b4e22c099a786ae6d660d9409bee032c7fa8R44), user agent looks like this:
```
ApifyClient/2.9.8 (Darwin; Node/v22.11.0); isAtHome/false; SDK/3.1.1; Crawlee/3.11.5
```
Closes #331
> feat: add SDK and Crawlee version to the `ApifyClient`'s user agent

- packages/apify/src/actor.ts
- test/apify/actor.test.ts
Ports the property injection from [Crawlee's `RequestQueue.open()`](https://github.com/apify/crawlee/blob/1e59f1b53176ec45ad42dbc8590d9f3626debacb/packages/core/src/storages/request_provider.ts#L835).
Closes #337
> fix: load `initialCount` in `openRequestQueue()`

- packages/apify/src/actor.ts
We can't use `Actor.reboot()` inside a `migrating` event handler, because it internally calls all the handlers for the `migrating` event, so calling that on the `migrating` event would get into an infinite loop. This fixes it by allowing the reboot to be called only once.
> fix: prevent reboot loops

- packages/apify/src/charging.ts
`Configuration.get('maxTotalChargeUsd')` seems to return an empty string in some platform runs - this is a workaround for that.
> fix: Add workaround for incorrect handling of maxTotalChargeUsd

- package-lock.json
- packages/apify/package.json
- packages/apify/src/charging.ts
- packages/apify/src/configuration.ts
- test/apify/actor.test.ts
The `ACTOR_MAX_TOTAL_CHARGE_USD` env var wasnt properly marked as integer, and the fallback to infinity wasn't working in case the value was an empty string, since `??` fallbacks only for null/undefined values.
> fix: ensure `maxTotalChargeUsd` is correctly mapped to number, consider empty string as infinity

- package-lock.json
- packages/actor-scraper/camoufox-scraper/.actor/actor.json
- packages/actor-scraper/camoufox-scraper/.dockerignore
- packages/actor-scraper/camoufox-scraper/Dockerfile
- packages/actor-scraper/camoufox-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/camoufox-scraper/README.md
- packages/actor-scraper/camoufox-scraper/package.json
- packages/actor-scraper/camoufox-scraper/src/internals/consts.ts
- packages/actor-scraper/camoufox-scraper/src/internals/crawler_setup.ts
- packages/actor-scraper/camoufox-scraper/src/main.ts
- packages/actor-scraper/camoufox-scraper/tsconfig.json
Adds a Playwright Scraper port that uses Camoufox as the browser backend [via Camoufox JS](https://github.com/apify/camoufox-js/)).
This PR removes the original `useChrome` and `browserLauncher` options from the new input schema (as the only available browser is now Camoufox) and adds a `Camoufox options` input section, which maps to the [options that can be passed to Camoufox](https://github.com/apify/camoufox-js/blob/286debe0171ad2b1870ac23869b68b1e4f16e47a/src/utils.ts#L300).
> feat: add Camoufox-based generic Actor

- packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts
- packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts
- packages/apify/src/proxy_configuration.ts
- test/apify/events.test.ts
- I cherry-picked changes by @danpoletaev from https://github.com/apify/apify-sdk-js/pull/358 so that we can have a green `master` branch ASAP
- There was an issue in PlatformEventManager tests likely caused by https://github.com/apify/apify-shared-js/pull/496. Making a new `PlatformEventManager` instance for each test fixed it.
> chore: Update Crawlee and fix related issues

- .github/workflows/release-generic-actors-v2.yaml
- .github/workflows/release-generic-actors.yaml
- packages/actor-scraper/cheerio-scraper/.actor/actor.json
- packages/actor-scraper/jsdom-scraper/.actor/actor.json
- packages/actor-scraper/playwright-scraper/.actor/actor.json
- packages/actor-scraper/puppeteer-scraper/.actor/actor.json
- packages/actor-scraper/web-scraper/.actor/actor.json
- packages/actor-scraper/web-scraper/apify.json
Adds a manual-dispatch CI workflow for running generic Actor builds on Apify.
> chore(ci): add automatic release workflow for generic Actors

- .github/workflows/release-generic-actors.yaml
- package-lock.json
- packages/actor-scraper/camoufox-scraper/Dockerfile
- packages/actor-scraper/camoufox-scraper/package.json
Fixes the missing pieces from #380 . Fixes the Camoufox scraper internals and dependencies.
> chore(ci): fix automatic Actor build versioning

- packages/actor-scraper/camoufox-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/cheerio-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/jsdom-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/playwright-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/puppeteer-scraper/INPUT_SCHEMA.json
- packages/actor-scraper/web-scraper/INPUT_SCHEMA.json
Because of the recent Crawlee homepage redesign, the generic Actors only scrape one webpage (`crawlee.dev`) and stop now. This PR appends `/js/` to the respective input options and restores the original behaviour.
| ![image](https://github.com/user-attachments/assets/f14ce62d-1544-4b89-90f4-200d85dcb117) |
|--|
| *Default behaviour now* |
> chore: align generic scraper defaults with new `crawlee.dev` structure

- packages/apify/src/proxy_configuration.ts
- test/apify/proxy_configuration.test.ts
- Fetch proxy password from `/user/me` using `APIFY_ENV_VARS.TOKEN` only when `APIFY_ENV_VARS.PROXY_PASSWORD` is not provided
- Proxy init no longer logs when there is a difference between the proxy password from the environmental variable and the one obtained from the API, since only one is going to be taken into consideration. When running on Apify, the passwords will always be different. 
- should solve the second part of: https://console.apify.com/actors/RB9HEZitC8hIUXAha/issues/exVPDR4pOsgqlkE5T
Closes [#20502](https://github.com/apify/apify-core/issues/20502)
> fix: prefer proxy password from env var

- packages/actor-scraper/camoufox-scraper/Dockerfile
- packages/actor-scraper/camoufox-scraper/package.json
Replaces the base image for Camoufox Scraper with the newly created `actor-node-playwright-camoufox`.
[Test run](https://console.apify.com/view/runs/FhQqppAgSSQYcHVHa)
> chore: use Camoufox base Docker image in Camoufox Scraper

- package-lock.json
- package.json
- packages/apify/package.json
To support decryption of secret object/array - https://github.com/apify/apify-shared-js/pull/515
> chore: update apify/input_secrets version

- website/docusaurus.config.js
Uses the `git-cliff`-generated CHANGELOG.md file from the root of the repository to render the changelog in the docs. This unifies all the changelogs and simplifies the docs rendering process.
Closes #417
> chore: render `CHANGELOG.md` file in the docs

- packages/actor-scraper/web-scraper/README.md
> docs: added video to readme for web scraper

- packages/apify/src/actor.ts
Adds a warning on a non-initialized Actor on `useState`, `exit`, `reboot` and `setStatusMessage` method calls.
> fix: ensure the `Actor` instance is initialized while calling its methods
