README.md, package.json, packages/apify/README.md
Also related to https://github.com/apify/crawlee/pull/1413
=> docs: replace Actor SDK with Apify SDK

.github/workflows/test-e2e.yml
Will run it first to ensure it works and merge if it passes
EDIT: Marked as draft as we need to discuss what to do about the tests we would run and also need to do some more configuration for them
=> chore: login to testing account for e2e tests

packages/actor-scraper/playwright-scraper/README.md
- remove table of contents
- fix one link
=> docs: update playwright-scraper readme

packages/apify/src/actor.ts
This fixes the actor side of https://github.com/apify/crawlee/issues/1463
For the crawlee only side, I'll open up a PR there
=> fix: use correct event manager for actor methods

package-lock.json, package.json
This went easier than expected here
=> chore(deps): bump to ts 4.8

package-lock.json, packages/actor-scraper/cheerio-scraper/.dockerignore, packages/actor-scraper/cheerio-scraper/Dockerfile, packages/actor-scraper/cheerio-scraper/INPUT_SCHEMA.json, packages/actor-scraper/cheerio-scraper/README.md, packages/actor-scraper/cheerio-scraper/package.json, packages/actor-scraper/cheerio-scraper/src/internals/consts.ts, packages/actor-scraper/cheerio-scraper/src/internals/crawler_setup.ts, packages/actor-scraper/playwright-scraper/.dockerignore, packages/actor-scraper/playwright-scraper/Dockerfile, packages/actor-scraper/playwright-scraper/package.json
- Cheerio - should be good. There's nothing major we added to it right? I added globs to input, added that pseudo URLs are deprecated, update the links in the readme, etc. Tried to build/run it - seems ok.
- Playwright - updated the packages too (to have the same TS deps, etc) + updated docker file.
P.S.: I use node 16 there, or should we already use 18?
=> chore: update cheerio scraper + update pw scraper deps

package-lock.json, package.json, packages/actor-scraper/cheerio-scraper/README.md, packages/actor-scraper/cheerio-scraper/package.json, packages/actor-scraper/playwright-scraper/README.md, packages/actor-scraper/playwright-scraper/package.json, packages/actor-scraper/playwright-scraper/src/internals/crawler_setup.ts, packages/actor-scraper/puppeteer-scraper/Dockerfile, packages/actor-scraper/puppeteer-scraper/INPUT_SCHEMA.json, packages/actor-scraper/puppeteer-scraper/README.md, packages/actor-scraper/puppeteer-scraper/package.json, packages/actor-scraper/puppeteer-scraper/src/internals/consts.ts, packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts, packages/actor-scraper/web-scraper/Dockerfile, packages/actor-scraper/web-scraper/INPUT_SCHEMA.json, packages/actor-scraper/web-scraper/README.md, packages/actor-scraper/web-scraper/package.json, packages/actor-scraper/web-scraper/src/internals/consts.ts, packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts, packages/apify/package.json, packages/scraper-tools/package.json, packages/scraper-tools/src/context.ts, packages/scraper-tools/src/tools.ts
- add globs
- update READMEs
- update packages
=> feat: update the scrapers

package-lock.json, packages/actor-scraper/web-scraper/package.json, packages/actor-scraper/web-scraper/tsconfig.json
- pin puppeteer dependency to version 14
- add `@types/content-type` to deps
- add `"lib": ["dom"]` to ts-config
=> chore: fix web scraper

packages/apify/package.json
=> fix(apify): add `@apify/timeout` to dependencies

packages/apify/src/actor.ts
=> feat: warn about actor not being initialized before using storage methods

.github/workflows/release.yml, lerna.json, package.json, scripts/actions/markPrivate.mjs, scripts/actions/unmarkPrivate.mjs
HOPEFULLY never breaks :(
Note: first release might break the current changelog. Subsequent releases won't.
=> chore(ci): new release pipeline

packages/actor-scraper/playwright-scraper/Dockerfile, packages/actor-scraper/playwright-scraper/INPUT_SCHEMA.json, packages/actor-scraper/playwright-scraper/src/internals/consts.ts, packages/actor-scraper/playwright-scraper/src/internals/crawler_setup.ts, packages/actor-scraper/puppeteer-scraper/Dockerfile, packages/actor-scraper/puppeteer-scraper/INPUT_SCHEMA.json, packages/actor-scraper/puppeteer-scraper/src/internals/consts.ts, packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts
Handles a long lasting request. I would love if you had any better descriptions for the option, as I don't fully know how to describe it past...just linking to an article explaining it
=> feat(Puppeteer/PlaywrightScraper): add support for headful crawling

packages/apify/src/actor.ts
=> docs: add jsdoc annotations for Actor.exit(), .fail()

packages/actor-scraper/web-scraper/README.md
Added a FAQ section at the bottom to improve ranking. We are ranking quite badly for web scraper keyword lately. Let's see if this helps.
=> docs: Update README.md

.eslintrc.json, package-lock.json, package.json, packages/actor-scraper/playwright-scraper/INPUT_SCHEMA.json, packages/actor-scraper/playwright-scraper/package.json, packages/actor-scraper/playwright-scraper/src/internals/consts.ts, packages/actor-scraper/playwright-scraper/src/internals/crawler_setup.ts, packages/actor-scraper/puppeteer-scraper/INPUT_SCHEMA.json, packages/actor-scraper/puppeteer-scraper/package.json, packages/actor-scraper/puppeteer-scraper/src/internals/consts.ts, packages/actor-scraper/puppeteer-scraper/src/internals/crawler_setup.ts, packages/actor-scraper/web-scraper/INPUT_SCHEMA.json, packages/actor-scraper/web-scraper/package.json, packages/actor-scraper/web-scraper/src/internals/consts.ts, packages/actor-scraper/web-scraper/src/internals/crawler_setup.ts
Closes #208 
Probably needs some second thought on the cookie closing - the WCC actor has a thought-through waiting logic, which we have to(?) supply with ugly hard waits here.
=> refactor: port WCC features to generic (PW/PP/Web) scraper actors

packages/actor-scraper/web-scraper/INPUT_SCHEMA.json
As discussed here: https://apifier.slack.com/archives/CD0SF6KD4/p1687950625201129
=> docs: [web-scraper] add tips on how to scrape only Start URLs

package-lock.json, package.json, packages/apify/src/actor.ts, test/e2e/tools.mjs
This is a step towards changing the default behaviour of `purgeDefaultStorages` to clear storages each time it gets called.
=> chore: set `onlyPurgeOnce` to `true` explicitly for `purgeDefaultStorages`

package-lock.json, packages/apify/package.json, packages/apify/src/actor.ts, test/apify/actor.test.ts
=> feat: Use `.reboot()`  instead of `.metamorph()` for reboot

packages/apify/src/actor.ts
Also adds timeout handler around `Actor.setStatusMessage()`.
=> fix: add more logging to `Actor.init` and `Actor.exit`

website/docusaurus.config.js
Requested by @OlikEten as it helps the mktg team to edit the docs faster.
=> docs: add "Edit this Page" link to the docs

packages/apify/src/actor.ts
Basically, moved over all what was left from APIFY_ENV_VARS and searched through docs for known descriptions
Closes #170
=> docs: add more values to ApifyEnv

package-lock.json, package.json, packages/apify/package.json
as discussed in https://github.com/apify/crawlee/pull/2339
=> chore: bump `apify-client`

.github/workflows/docs.yaml
Adds Smartlook token for docs build
=> fix: Smartlook for docs build token [internal]

packages/actor-scraper/web-scraper/INPUT_SCHEMA.json
https://apify.slack.com/archives/C0L33UM7Z/p1717494874171389
=> docs: update cookies-related links

package-lock.json, package.json, packages/apify/src/proxy_configuration.ts, test/apify/proxy_configuration.test.ts
Related: https://github.com/apify/crawlee/issues/2696
=> fix: decode special characters in proxy `username` and `password`

packages/apify/src/configuration.ts
This PR introduces a new environment variable and also changes the default number of standby port to 4321.
=> feat: add standby URL, change default port

package-lock.json, packages/actor-scraper/cheerio-scraper/CHANGELOG.md, packages/actor-scraper/jsdom-scraper/CHANGELOG.md, packages/actor-scraper/playwright-scraper/CHANGELOG.md, packages/actor-scraper/puppeteer-scraper/CHANGELOG.md, packages/actor-scraper/web-scraper/CHANGELOG.md
bumps to the latest got scraping to resolve issues with special chars in proxy URLs
=> chore: update generic scrapers

.github/workflows/check-pr-title.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml, .github/workflows/test-and-release.yaml, .github/workflows/test-e2e.yaml
Fixes the recent failing CI tests. See https://github.com/apify/crawlee/pull/2816 for more details.
=> chore(ci): pin Ubuntu verrsion

packages/apify/src/utils.ts
Related: https://apify.slack.com/archives/CD0SF6KD4/p1744193806253989
Closes #375
=> fix: improve check for crawlee version mismatch

packages/apify/src/configuration.ts
This is needed for crawlee v4 which is native ESM.
=> fix: improve extension of `Configuration` class to fix issues in native ESM projects

packages/apify/src/actor.ts, packages/apify/src/charging.ts
=> docs: Improve ChargeResult and ChargeOptions documentation

website/src/pages/index.module.css
fixes tagline overlap (reported [here](https://apify.slack.com/archives/C0L33UM7Z/p1752206692759679))
=> fix: tagline overlap

packages/actor-scraper/camoufox-scraper/.actor/actor.json, packages/actor-scraper/cheerio-scraper/.actor/actor.json, packages/actor-scraper/jsdom-scraper/.actor/actor.json, packages/actor-scraper/playwright-scraper/.actor/actor.json, packages/actor-scraper/puppeteer-scraper/.actor/actor.json, packages/actor-scraper/web-scraper/.actor/actor.json
=> refactor: default to the `Output` tab in generic scrapers
